// ClarityValue branded types
declare const brand: unique symbol;
export type Branded<T, B> = T & { readonly [brand]: B };
export type UIntBrand = Branded<bigint, 'UInt'>;
export type IntBrand = Branded<bigint, 'Int'>;
export type BoolBrand = Branded<boolean, 'Bool'>;
export type StringAsciiBrand = Branded<string, 'StringAscii'>;
export type StringUtf8Brand = Branded<string, 'StringUtf8'>;
export type BufferBrand = Branded<Uint8Array, 'Buffer'>;
export type ClarityValueType = 'uint' | 'int' | 'bool' | 'string-ascii' | 'string-utf8' | 'buffer' | 'list' | 'tuple' | 'principal' | 'contract' | 'none' | 'some' | 'ok' | 'err';
export interface TypedClarityValue<T extends ClarityValueType, V> {
  type: T;
  value: V;
}
export const CV_TYPE_CONST_1 = 1;
export const CV_TYPE_CONST_2 = 2;
export const CV_TYPE_CONST_3 = 3;
export const CV_TYPE_CONST_4 = 4;
export const CV_TYPE_CONST_5 = 5;
export const CV_TYPE_CONST_6 = 6;
export const CV_TYPE_CONST_7 = 7;
export const CV_TYPE_CONST_8 = 8;
export const CV_TYPE_CONST_9 = 9;
export const CV_TYPE_CONST_10 = 10;
export const CV_TYPE_CONST_11 = 11;
export const CV_TYPE_CONST_12 = 12;
export const CV_TYPE_CONST_13 = 13;
export const CV_TYPE_CONST_14 = 14;
export const CV_TYPE_CONST_15 = 15;
export const CV_TYPE_CONST_16 = 16;
export const CV_TYPE_CONST_17 = 17;
export const CV_TYPE_CONST_18 = 18;
export const CV_TYPE_CONST_19 = 19;
export const CV_TYPE_CONST_20 = 20;
export const CV_TYPE_CONST_21 = 21;
export const CV_TYPE_CONST_22 = 22;
export const CV_TYPE_CONST_23 = 23;
export const CV_TYPE_CONST_24 = 24;
export const CV_TYPE_CONST_25 = 25;
export const CV_TYPE_CONST_26 = 26;
export const CV_TYPE_CONST_27 = 27;
export const CV_TYPE_CONST_28 = 28;
export const CV_TYPE_CONST_29 = 29;
export const CV_TYPE_CONST_30 = 30;
export const CV_TYPE_CONST_31 = 31;
export const CV_TYPE_CONST_32 = 32;
